### PR TITLE
Adds OAStackViewProxy to support native UIStackView in iOS 9

### PR DESCRIPTION
**Pull request by natanrolnik**
For now, it only supports it in code

### CODE REVIEW

**Comment by natanrolnik** [comment]
As mentioned in #2 - I preferred to do the UIView approach.

All properties needed to be declared and the setters pass the property to the correct stack view (native or backwards compatible).
The methods declared in the interface didn't need to be implemented, as the class implements `methodSignatureForSelector:` and `forwardInvocation`.

**Comment by natanrolnik** [comment]
And bear in mind it doesn't support interface builder yet.

**Comment by nsomar** [comment]
That is a nice approach, Thanks!
Do you think you can add a simple test (preferably on a new spec file)?

**Comment by natanrolnik** [comment]
Hey Omar! I'll try to add it soon.

**Comment by nsomar** [comment]
Please also don't forget to rebase since I fixed the test failing issue in iOS7. Again wonderful addition, I think we can expand on it to have a seamless iOS 9 integration :)

**Comment by nsomar** [comment]
Hey, Any updates on this, I can add the tests and rebase in the weekend if you want.

**Comment by natanrolnik** [comment]
Hey Omar! I tried to rebase a few days ago, but had some problems (did you change the file tree?). If you could do it, that would be awesome.

**Comment by nsomar** [comment]
Sure I will do that no problem!
Yeah, Sadly I added some files, and moved some code around. Anyways, I will rebase and add some tests. 
I will create a pull request with the tests so that you can give me your opinion on wether they cover all your planned scenarios. I will share them in a new branch prior to merge.
Does that sound good to you?

Thanks for the great addition btw!

**Comment by k06a** [comment]
@natanrolnik maybe you'll suggest me how to use native NSLayoutAnchor API category if API is available? https://github.com/k06a/MissingAnchors/blob/master/Pod/Classes/ABLayoutAnchor/UIView%2BABLayoutAnchor.m

**Comment by natanrolnik** [comment]
Hm, interesting... I will try to take a look.

**Comment by natanrolnik** [comment]
Closing as #87 was merged already

**Pull request closed without merging**
