### PR TITLE
OAStackViewDistributionFillProportionally implemented

### PR DESCRIPTION
**Pull request by bartvandendriessche**
Did a quick draft implementation for the FillProportionally distribution.

Also updated the Example project so that:
- Distribution strategies can be switched
- Buttons have different `intrinsicContentSize`

### CODE REVIEW

**Comment by nsomar** [comment]
Hello, super cool addition :+1: 
Are you planning on adding some test coverage for these distribution? If not, then I might add coverage and merge it over the weekend.

**Comment by bartvandendriessche** [comment]
Heya, not sure if I'll have time over the weekend to add tests. 

If I do, I'll try to add some tests. If you've already added them by then, I might try to fill in some other feature, so by all means, don't wait for me :)

**Comment by bartvandendriessche** [comment]
Quick side note, the tests check that the proportional view is within a range of 1 point of the 'calculated reference value', because AutoLayout tries prevent misaligned views (i.e. it will round).

**Comment by nsomar** [comment]
Wonderfull addition :+1: merging right away :)

**Pull request merged**
