### PR TITLE
Added generics to NSArrays for Swift support

### PR DESCRIPTION
**Pull request by harlanhaskins**

### CODE REVIEW

**Comment by delebedev** [comment]
thanks @harlanhaskins! can you update your branch with current master please? It should fix travis.
I am not sure however if everybody is using Xcode7 already, maybe we need one more release for this, what do you think?

**Comment by nsomar** [comment]
Hello @harlanhaskins, @garnett I am going to take this PR and merge it manually

**Comment by nsomar** [comment]
Merged!

**Comment by harlanhaskins** [comment]
Thanks so much!

**Pull request closed without merging**
