### PR TITLE
Add layoutMargins to proxy

### PR DESCRIPTION
**Pull request by joemasilotti**
I missed this property in #87.

### CODE REVIEW

**Comment by joemasilotti** [comment]
Ah, I forgot this project supports iOS 7. I'm looking in to this now.

**Comment by joemasilotti** [comment]
OK, this is passing and ready for review now, @oarrabi  👍

**Comment by nsomar** [comment]
Cool!

**Comment by joemasilotti** [comment]
Thanks! What are your thoughts on cutting a new release, say 1.1.0, with the proxy?

**Pull request merged**
