### PR TITLE
[WIP] Adding baseline align support

### PR DESCRIPTION
**Pull request by Thomvis**
I am working on adding baseline align support, because I needed it. This requires a bit of a change in the way the alignment strategies are called, because the alignment is between views and not between the view and the stack view.

I'm looking for feedback on the following points:
- [ ] Is this how UIStackView baseline aligns labels? (haven't tried it myself yet)
- [ ] What do you think about the way I've extended the alignment strategy?
- [ ] To test this, new (UILabel based?) tests are needed. How do you want the test suite to grow?

### CODE REVIEW

**Comment by nsomar** [comment]
This looks amazing :+1: 
Do you think you will be able to add some unit test to cover these enums? If not, then I can add them on the weekend.

Thanks for your great addition :+1:  !!

**Comment by Thomvis** [comment]
#17 now contains a fix for an issue I discovered yesterday with this PR. Sorry that they're so intertwined. Let me know if I can help.

I won't have time this weekend, so feel free to merge to your likings.

**Comment by nsomar** [comment]
Hey,
Sorry for being super late. I just reviewed this PR and it looks very cool.
However, I ran a couple of tests on UIStackView and it seems that the baseline constraints works as following:

For this example consider the following image

screen shot 2015-07-05 at 00 55 05

In your implementation you are adding baseline constraint for button 2 in relation to 1, and button 3 in relation to 2, etc..
However, In UIStackView, baseline constraint are always added to the first view. So button 2 adds to 1 and button 3 to 1 etc..

The following is a po of the constraints added in UIStackView:

```
<NSLayoutConstraint:0x7f984ac40510 'UI-alignment' UIButton:0x7f984ad0e310'1'.lastBaseline == UIButton:0x7f984ad11670'2'.lastBaseline>,
<NSLayoutConstraint:0x7f984ac42f80 'UI-alignment' UIButton:0x7f984ad0e310'1'.lastBaseline == UIButton:0x7f984ad11e80'3'.lastBaseline>,
<NSLayoutConstraint:0x7f984ac43740 'UI-alignment' UIButton:0x7f984ad0e310'1'.lastBaseline == UILabel:0x7f984ad12460'adasdsdsadasdasda'.lastBaseline>,
```

I think we should consider implementing the same idea as with UIStackView. What is your input on this?
Also, what is your general idea on what unit tests can we use to assert the constraints? should we go with frames or with constraints?

**Comment by nsomar** [comment]
@Thomvis Hey, I will be trying to merge both your great PR's this weekend. About my last question. If you dont have free time, I can totally tackle it.

**Comment by Thomvis** [comment]
@oarrabi sorry, but I won't have time soon to improve this further. I do hope that we can eventually merge more changes from https://github.com/Thomvis/OAStackView back to this repo, but I understand that this will take time from me (if you agree with those changes ;)).

**Comment by nsomar** [comment]
Thanks for the addition, I added some specs and merged this PR, Wonderfull work!

**Pull request closed without merging**
